export function generateDataLayerDefinitions(
  industry: "ecommerce" | "saas" | "leadgen" | "content"
): string {
  if (industry === "ecommerce") {
    return `// dataLayer.d.ts - Generated by gtm-tag-architect for E-Commerce
export interface EcommerceItem {
  item_id: string;
  item_name: string;
  price: number;
  quantity?: number;
  item_category?: string;
  item_variant?: string;
}

export interface EcommerceEvents {
  view_item_list: {
    item_list_id?: string;
    item_list_name?: string;
    items: EcommerceItem[];
  };
  view_item: {
    currency: string;
    value: number;
    items: EcommerceItem[];
  };
  add_to_cart: {
    currency: string;
    value: number;
    items: EcommerceItem[];
  };
  begin_checkout: {
    currency: string;
    value: number;
    items: EcommerceItem[];
  };
  purchase: {
    transaction_id: string;
    currency: string;
    value: number;
    tax?: number;
    shipping?: number;
    items: EcommerceItem[];
  };
}

export type GtmEvent =
  | { event: "page_view"; page_path: string; page_title: string }
  | { [K in keyof EcommerceEvents]: { event: K; ecommerce: EcommerceEvents[K] } }[keyof EcommerceEvents];

declare global {
  interface Window {
    dataLayer: Record<string, any>[];
  }
}

export function pushGtmEvent<T extends GtmEvent>(payload: T): void {
  if (typeof window !== "undefined" && window.dataLayer) {
    // Clear previous ecommerce object before pushing new one to prevent state bleed
    if ("ecommerce" in payload) {
      window.dataLayer.push({ ecommerce: null });
    }
    window.dataLayer.push(payload);
  }
}
`;
  } else if (industry === "saas") {
    return `// dataLayer.d.ts - Generated by gtm-tag-architect for SaaS / Product Analytics
export interface SaasEvents {
  view_pricing: {
    plan_tier_selected?: string;
    billing_period: "monthly" | "annual";
  };
  start_trial: {
    plan_name: string;
    trial_duration_days: number;
  };
  sign_up: {
    method: "email" | "google" | "github" | "sso";
    user_id_hashed?: string;
  };
  feature_used: {
    feature_name: string;
    module: string;
  };
  subscription_activated: {
    transaction_id: string;
    plan_name: string;
    value: number;
    currency: string;
    billing_cycle: "monthly" | "annual";
  };
}

export type GtmEvent =
  | { event: "page_view"; page_path: string; page_title: string }
  | { [K in keyof SaasEvents]: { event: K } & SaasEvents[K] }[keyof SaasEvents];

declare global {
  interface Window {
    dataLayer: Record<string, any>[];
  }
}

export function pushGtmEvent<T extends GtmEvent>(payload: T): void {
  if (typeof window !== "undefined" && window.dataLayer) {
    window.dataLayer.push(payload);
  }
}
`;
  } else {
    return `// dataLayer.d.ts - Generated by gtm-tag-architect for Lead Generation
export interface LeadGenEvents {
  view_case_study: {
    case_study_slug: string;
    industry_category: string;
  };
  click_cta: {
    cta_text: string;
    cta_location: "header" | "footer" | "in_body" | "floating";
  };
  submit_lead_form: {
    form_id: string;
    company_size?: string;
    service_interest?: string;
  };
  book_meeting: {
    meeting_type: string;
    calendar_provider: "calendly" | "hubspot" | "custom";
  };
}

export type GtmEvent =
  | { event: "page_view"; page_path: string; page_title: string }
  | { [K in keyof LeadGenEvents]: { event: K } & LeadGenEvents[K] }[keyof LeadGenEvents];

declare global {
  interface Window {
    dataLayer: Record<string, any>[];
  }
}

export function pushGtmEvent<T extends GtmEvent>(payload: T): void {
  if (typeof window !== "undefined" && window.dataLayer) {
    window.dataLayer.push(payload);
  }
}
`;
  }
}
