export function generateDataLayerDefinitions(
  industry: "portfolio" | "ecommerce" | "saas" | "leadgen" | "content",
  framework: "typescript" | "php" | "wordpress" | "laravel" | "symfony" | "vanilla" = "typescript"
): string {
  if (framework === "php" || framework === "wordpress" || framework === "laravel" || framework === "symfony") {
    return `<?php
declare(strict_types=1);

/**
 * GtmDataLayer.php - Generated by gtm-tag-architect for PHP (${framework.toUpperCase()})
 * Industry: ${industry.toUpperCase()}
 * 
 * Provides server-side dataLayer event dispatching and inline script rendering.
 */

namespace App\\Analytics;

class GtmDataLayer
{
    private static array $queuedEvents = [];

    /**
     * Push a structured event into the server-side queue.
     * @param string $event Event name (e.g. 'purchase', 'sign_up', 'contact_form_submitted')
     * @param array $payload Additional event parameters or ecommerce object
     */
    public static function push(string $event, array $payload = []): void
    {
        if (isset($payload['ecommerce'])) {
            // Push ecommerce: null clearance first to prevent state bleeding
            self::$queuedEvents[] = ['ecommerce' => null];
        }
        self::$queuedEvents[] = array_merge(['event' => $event], $payload);
    }

    /**
     * Helper for tracking lead form or contact form submissions.
     */
    public static function trackLeadForm(string $formId, bool $success = true): void
    {
        self::push('contact_form_submitted', [
            'form_id' => $formId,
            'success' => $success,
        ]);
    }

    /**
     * Render the inline <script> tag initializing dataLayer and flushing queued events.
     * Place this immediately before the GTM container script in your <head>.
     */
    public static function renderScript(): string
    {
        if (empty(self::$queuedEvents)) {
            return "<script>window.dataLayer = window.dataLayer || [];</script>";
        }

        $json = json_encode(self::$queuedEvents, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_UNESCAPED_SLASHES);
        self::$queuedEvents = [];

        return "<script>\\n" .
               "  window.dataLayer = window.dataLayer || [];\\n" .
               "  (function(){\\n" .
               "    var serverEvents = {$json};\\n" .
               "    for (var i = 0; i < serverEvents.length; i++) {\\n" .
               "      window.dataLayer.push(serverEvents[i]);\\n" .
               "    }\\n" .
               "  })();\\n" .
               "</script>";
    }
}

/* Framework Integration Examples:

1. WordPress (functions.php):
   add_action('wp_head', function() {
       echo \\App\\Analytics\\GtmDataLayer::renderScript();
   }, 1);

2. Laravel (resources/views/layouts/app.blade.php):
   <head>
       {!! \\App\\Analytics\\GtmDataLayer::renderScript() !!}
       <!-- Google Tag Manager --> ...
   </head>

3. Symfony (templates/base.html.twig):
   <head>
       {{ gtm_script()|raw }}
   </head>
*/
`;
  }
  if (industry === "ecommerce") {
    return `// dataLayer.d.ts - Generated by gtm-tag-architect for E-Commerce
export interface EcommerceItem {
  item_id: string;
  item_name: string;
  price: number;
  quantity?: number;
  item_category?: string;
  item_variant?: string;
}

export interface EcommerceEvents {
  view_item_list: {
    item_list_id?: string;
    item_list_name?: string;
    items: EcommerceItem[];
  };
  view_item: {
    currency: string;
    value: number;
    items: EcommerceItem[];
  };
  add_to_cart: {
    currency: string;
    value: number;
    items: EcommerceItem[];
  };
  begin_checkout: {
    currency: string;
    value: number;
    items: EcommerceItem[];
  };
  purchase: {
    transaction_id: string;
    currency: string;
    value: number;
    tax?: number;
    shipping?: number;
    items: EcommerceItem[];
  };
}

export type GtmEvent =
  | { event: "page_view"; page_path: string; page_title: string }
  | { [K in keyof EcommerceEvents]: { event: K; ecommerce: EcommerceEvents[K] } }[keyof EcommerceEvents];

declare global {
  interface Window {
    dataLayer: Record<string, any>[];
  }
}

export function pushGtmEvent<T extends GtmEvent>(payload: T): void {
  if (typeof window !== "undefined" && window.dataLayer) {
    // Clear previous ecommerce object before pushing new one to prevent state bleed
    if ("ecommerce" in payload) {
      window.dataLayer.push({ ecommerce: null });
    }
    window.dataLayer.push(payload);
  }
}
`;
  } else if (industry === "saas") {
    return `// dataLayer.d.ts - Generated by gtm-tag-architect for SaaS / Product Analytics
export interface SaasEvents {
  view_pricing: {
    plan_tier_selected?: string;
    billing_period: "monthly" | "annual";
  };
  start_trial: {
    plan_name: string;
    trial_duration_days: number;
  };
  sign_up: {
    method: "email" | "google" | "github" | "sso";
    user_id_hashed?: string;
  };
  feature_used: {
    feature_name: string;
    module: string;
  };
  subscription_activated: {
    transaction_id: string;
    plan_name: string;
    value: number;
    currency: string;
    billing_cycle: "monthly" | "annual";
  };
}

export type GtmEvent =
  | { event: "page_view"; page_path: string; page_title: string }
  | { [K in keyof SaasEvents]: { event: K } & SaasEvents[K] }[keyof SaasEvents];

declare global {
  interface Window {
    dataLayer: Record<string, any>[];
  }
}

export function pushGtmEvent<T extends GtmEvent>(payload: T): void {
  if (typeof window !== "undefined" && window.dataLayer) {
    window.dataLayer.push(payload);
  }
}
`;
  } else if (industry === "portfolio") {
    return `// dataLayer.d.ts - Generated by gtm-tag-architect for Technical Portfolio & Peer Engagement
export interface PortfolioTrackingEvents {
  section_viewed: {
    section_name: "hero" | "roles" | "enterprise_projects" | "builds" | "wins" | "stack" | "certifications" | "faq" | "contact";
    time_spent_seconds?: number;
  };
  credential_verified: {
    cert_title: string;
    verify_url: string;
  };
  external_project_clicked: {
    project_name: string;
    destination_url: string;
    project_type: "production" | "open_source";
  };
  social_channel_clicked: {
    channel: "github" | "linkedin" | "facebook" | "email";
    destination_url: string;
  };
  contact_form_started: {
    form_id: string;
  };
  contact_form_submitted: {
    form_id: string;
    success: boolean;
    error_message?: string;
  };
  article_reading_milestone: {
    post_slug: string;
    post_title: string;
    milestone_percent: 25 | 50 | 75 | 100;
  };
  article_code_copied: {
    post_slug: string;
    code_language?: string;
  };
  back_to_top_clicked: {
    page_path: string;
  };
}

export type GtmEvent =
  | { event: "page_view"; page_path: string; page_title: string }
  | { [K in keyof PortfolioTrackingEvents]: { event: K } & PortfolioTrackingEvents[K] }[keyof PortfolioTrackingEvents];

declare global {
  interface Window {
    dataLayer?: Record<string, any>[];
  }
}

export function pushGtmEvent<T extends GtmEvent>(payload: T): void {
  if (typeof window !== "undefined" && window.dataLayer) {
    window.dataLayer.push(payload);
  }
}
`;
  } else {
    return `// dataLayer.d.ts - Generated by gtm-tag-architect for Lead Generation
export interface LeadGenEvents {
  view_case_study: {
    case_study_slug: string;
    industry_category: string;
  };
  click_cta: {
    cta_text: string;
    cta_location: "header" | "footer" | "in_body" | "floating";
  };
  submit_lead_form: {
    form_id: string;
    company_size?: string;
    service_interest?: string;
  };
  book_meeting: {
    meeting_type: string;
    calendar_provider: "calendly" | "hubspot" | "custom";
  };
}

export type GtmEvent =
  | { event: "page_view"; page_path: string; page_title: string }
  | { [K in keyof LeadGenEvents]: { event: K } & LeadGenEvents[K] }[keyof LeadGenEvents];

declare global {
  interface Window {
    dataLayer: Record<string, any>[];
  }
}

export function pushGtmEvent<T extends GtmEvent>(payload: T): void {
  if (typeof window !== "undefined" && window.dataLayer) {
    window.dataLayer.push(payload);
  }
}
`;
  }
}
