import { AuditReport } from "../types/gtm.js";

export function generateMarkdownReport(report: AuditReport): string {
  const criticalCount = report.findings.filter((f) => f.severity === "critical").length;
  const warningCount = report.findings.filter((f) => f.severity === "warning").length;

  let badge = "🟢 EXCELLENT";
  if (report.healthScore < 50) badge = "🔴 CRITICAL DEFECTS";
  else if (report.healthScore < 80) badge = "🟡 NEEDS ATTENTION";

  let md = `# GTM Container Audit Report: ${report.containerName} (${report.publicId})

**Generated by GTM Tag Architect**
**Status:** ${badge} | **Health Score:** ${report.healthScore}/100

---

## Executive Summary
- **Total Tags:** ${report.totalTags}
- **Total Triggers:** ${report.totalTriggers}
- **Total Variables:** ${report.totalVariables}
- **Critical Issues:** ${criticalCount}
- **Warnings:** ${warningCount}

---

## Detailed Findings

`;

  if (report.findings.length === 0) {
    md += `> ✅ **Clean Baseline:** No duplicate measurement IDs, orphaned triggers, PII leakage, or render-blocking tags detected.\n\n`;
  } else {
    for (const f of report.findings) {
      const icon = f.severity === "critical" ? "🚨 [CRITICAL]" : f.severity === "warning" ? "⚠️ [WARNING]" : "ℹ️ [INFO]";
      md += `### ${icon} ${f.title}\n`;
      md += `- **ID:** \`${f.id}\` | **Category:** \`${f.category}\`\n`;
      md += `- **Description:** ${f.description}\n`;
      md += `- **Affected Entities:** ${f.affectedEntities.map((e) => `\`${e}\``).join(", ")}\n`;
      md += `- **Recommendation:** ${f.recommendation}\n\n`;
    }
  }

  md += `## Passed Verifications (${report.passedAudits.length})\n\n`;
  for (const p of report.passedAudits) {
    md += `- ✓ ${p}\n`;
  }

  md += `\n---\n*Report generated via gtm-tag-architect MCP toolset.*`;

  return md;
}

export function generateHtmlReport(report: AuditReport): string {
  const criticalCount = report.findings.filter((f) => f.severity === "critical").length;
  const warningCount = report.findings.filter((f) => f.severity === "warning").length;

  let scoreColor = "#10b981";
  if (report.healthScore < 50) scoreColor = "#ff4f7b";
  else if (report.healthScore < 80) scoreColor = "#ffbd2e";

  const findingsHtml = report.findings
    .map((f) => {
      const badgeColor = f.severity === "critical" ? "#ff4f7b" : f.severity === "warning" ? "#ffbd2e" : "#58a6ff";
      return `
      <div style="border: 2px solid #30363d; border-radius: 8px; padding: 16px; margin-bottom: 16px; background: #161b22;">
        <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px;">
          <h3 style="margin: 0; font-size: 16px; color: #f0f6fc;">${f.title}</h3>
          <span style="background: ${badgeColor}; color: #0d1117; font-weight: bold; font-size: 11px; padding: 4px 8px; border-radius: 4px; text-transform: uppercase;">
            ${f.severity}
          </span>
        </div>
        <p style="margin: 6px 0; color: #8b949e; font-size: 14px;">${f.description}</p>
        <p style="margin: 6px 0; font-size: 13px; color: #c9d1d9;"><strong>Affected:</strong> ${f.affectedEntities.map((e) => `<code style="background: #0d1117; padding: 2px 6px; border-radius: 4px; border: 1px solid #30363d;">${e}</code>`).join(" ")}</p>
        <p style="margin: 6px 0; font-size: 13px; color: #7ee787;"><strong>Recommendation:</strong> ${f.recommendation}</p>
      </div>`;
    })
    .join("\n");

  const passedHtml = report.passedAudits
    .map((p) => `<li style="margin: 6px 0; color: #3fb950; font-size: 14px;">✓ ${p}</li>`)
    .join("\n");

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>GTM Audit Report - ${report.containerName}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0d1117; color: #e6edf3; padding: 40px; margin: 0; line-height: 1.6; }
  .container { max-width: 900px; margin: 0 auto; }
  .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #30363d; padding-bottom: 20px; margin-bottom: 24px; }
  .score-badge { font-size: 32px; font-weight: bold; color: ${scoreColor}; background: #161b22; border: 2px solid ${scoreColor}; padding: 8px 18px; border-radius: 12px; }
  .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 24px; }
  .stat-card { background: #161b22; border: 1px solid #30363d; padding: 14px; border-radius: 8px; text-align: center; }
  .stat-num { font-size: 20px; font-weight: bold; color: #79c0ff; }
  .stat-label { font-size: 12px; color: #8b949e; text-transform: uppercase; }
</style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div>
        <h1 style="margin: 0; font-size: 24px;">${report.containerName}</h1>
        <p style="margin: 4px 0 0 0; color: #8b949e;">Public ID: ${report.publicId} • Generated by GTM Tag Architect</p>
      </div>
      <div class="score-badge">${report.healthScore}/100</div>
    </div>

    <div class="stats">
      <div class="stat-card"><div class="stat-num">${report.totalTags}</div><div class="stat-label">Total Tags</div></div>
      <div class="stat-card"><div class="stat-num">${report.totalTriggers}</div><div class="stat-label">Triggers</div></div>
      <div class="stat-card"><div class="stat-num" style="color: #ff4f7b;">${criticalCount}</div><div class="stat-label">Critical Defects</div></div>
      <div class="stat-card"><div class="stat-num" style="color: #ffbd2e;">${warningCount}</div><div class="stat-label">Warnings</div></div>
    </div>

    <h2 style="font-size: 18px; border-bottom: 1px solid #30363d; padding-bottom: 8px; margin-top: 32px;">Diagnostic Findings</h2>
    ${findingsHtml || '<p style="color: #3fb950;">No critical issues detected.</p>'}

    <h2 style="font-size: 18px; border-bottom: 1px solid #30363d; padding-bottom: 8px; margin-top: 32px;">Passed Verifications</h2>
    <ul style="list-style: none; padding-left: 0;">${passedHtml}</ul>
  </div>
</body>
</html>`;
}
